写了下基本的route信息
exxhentai/flask pull request #3
Opened 2019-07-30 07:55 UTC by zjdavid2

其他的东西还是要等到数据库finalize之后才能写

2019-07-31 08:53 UTC, r1235613 commented
你直接在Master上面開發嗎？

2019-07-31 08:54 UTC, zjdavid2 commented
> 你直接在Master上面開發嗎？

我没有这个repo的写权限，无法创建别的branch

2019-07-31 09:00 UTC, zjdavid2 commented
我可以创个branch开发，然后定期merge。不过得有这个repo的写权限

2019-07-31 15:37 UTC, linonetwo commented
用 PullRequest 蛮好的啊，这样你们可以互相看过了再 merge。

我把 @zjdavid2 你加进来了，这样你也可以合并 @r1235613  的 PR 了。

2019-08-02 12:28 UTC, r1235613 requested changes

2019-08-02 12:28 UTC, r1235613 commented on app/views/api.py
> +    json = request.get_json()
萬一進來的不是jsson這邊會直接炸掉哦？

2019-08-02 12:28 UTC, r1235613 commented on app/views/api.py
> +    json = request.get_json()
因為python有個模組叫`json`，不建議跟他撞名

2019-08-02 12:28 UTC, r1235613 commented on app/views/api.py
> +    words = json['word']
這樣做萬一找不到word的key程式一樣會炸，善用`get()`方法

2019-08-02 12:28 UTC, zjdavid2 commented on app/views/api.py
> +    json = request.get_json()
OK

2019-08-02 12:30 UTC, zjdavid2 commented
抱歉，我之前用的是Get 方法，刚刚才改到POST（因为感觉参数太多了），一时匆忙所以有些疏忽……

2019-08-02 12:35 UTC, r1235613 requested changes

2019-08-02 12:35 UTC, r1235613 commented on requirements.txt
>  itsdangerous==1.1.0
建議換用`jwt`，易於與其他語言通信

2019-08-02 12:36 UTC, r1235613 commented
慢慢來，ex復活了，寧願慢一點，也不要像日本的7-11 Pay上線兩天就被打下來

2019-08-04 12:09 UTC, r1235613 approved these changes
OK！

2019-08-04 12:09 UTC, merged

2019-08-04 12:12 UTC, r1235613 commented
是說，要不要把藍圖取個好一點的名字，例如search之類的，這個藍圖前綴就設為`search`，因為後續肯定會有其他類別的API例如`Auth`或是`go`之類的。

2019-08-04 12:15 UTC, zjdavid2 commented
没问题